# Generated by Django 3.2.16 on 2023-01-29 23:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='identifier',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='title')),
            ],
            options={
                'verbose_name': 'notebook',
                'verbose_name_plural': 'notebooks',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='identifier',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                (
                    'notebook',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to='notes.notebook',
                        verbose_name='notebook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ('notebook', 'title'),
                'unique_together': {('notebook', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='identifier',
                    ),
                ),
                ('offset', models.PositiveIntegerField(verbose_name='link offset')),
                ('length', models.PositiveIntegerField(verbose_name='link length')),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='references',
                        to='notes.note',
                        verbose_name='source note',
                    ),
                ),
                (
                    'target_note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='referenced_by',
                        to='notes.note',
                        verbose_name='target note',
                    ),
                ),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
                'ordering': ('note', 'offset'),
                'unique_together': {('note', 'target_note')},
            },
        ),
        migrations.CreateModel(
            name='NoteBookUserPermission',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='identifier',
                    ),
                ),
                (
                    'notebook',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_permissions',
                        to='notes.notebook',
                        verbose_name='notebook',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notebook_permissions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'notebook user permission',
                'verbose_name_plural': 'notebook user permissions',
                'ordering': ('notebook', 'user'),
                'unique_together': {('notebook', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='identifier',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='aliases',
                        to='notes.note',
                        verbose_name='note',
                    ),
                ),
            ],
            options={
                'verbose_name': 'alias',
                'verbose_name_plural': 'aliases',
                'ordering': ('note', 'title'),
                'unique_together': {('note', 'title')},
            },
        ),
    ]
