# Generated by Django 3.2.24 on 2024-02-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20230205_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='question',
            field=models.TextField(blank=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='target_note',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='references_to', to='notes.note', verbose_name='target note',
            ),
        ),
        migrations.AddField(
            model_name='note',
            name='referenced_notes',
            field=models.ManyToManyField(
                related_name='referencing_notes', through='notes.Reference',
                to='notes.Note', verbose_name='referenced notes',
            ),
        ),
    ]
