# Generated by Django 3.2.24 on 2024-02-29 23:59

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20240228_2322'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name='reference',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=3072, null=True, verbose_name='embedding'),
        ),
        migrations.AddField(
            model_name='reference',
            name='state',
            field=models.CharField(
                choices=[('checking_uniqueness', 'Checking uniqueness'), ('active', 'Active')],
                default='active', max_length=20, verbose_name='state',
            ),
        ),
    ]
