# Generated by Django 4.2.11 on 2024-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='generating_references',
            field=models.BooleanField(default=False, verbose_name='generating QA'),
        ),
    ]
