# Generated by Django 4.2.11 on 2024-04-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_generating_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='question',
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.CharField(
                choices=[('suggested', 'Suggested'), ('active', 'Active')],
                default='active', max_length=20, verbose_name='state',
            ),
        ),
        migrations.AlterField(
            model_name='reference',
            name='state',
            field=models.CharField(
                choices=[('suggested', 'Suggested'), ('active', 'Active')],
                default='active', max_length=20, verbose_name='state',
            ),
        ),
        migrations.AlterField(
            model_name='reference',
            name='target_note',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='references_to', to='notes.note', verbose_name='target note',
            ),
        ),
    ]
