name: Python application test with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: pgvector/pgvector:pg16
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgrespass
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python

      - name: Run pytest with coverage
        run: poetry run pytest --cov-report=xml --cov=gpt_drawer --cov=users --cov=notes --cov=djsfc --cov=admin_utils
        env:
          DATABASE_URL: postgresql://postgres:postgrespass@localhost:5432/gpt_drawer

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
